#!/bin/sh

# Xcode Cloud post-clone step.
#
# SmartEars.xcodeproj is generated by XcodeGen from project.yml and is NOT
# committed (it's gitignored). Xcode Cloud clones the repo before building, so we
# must regenerate the project here or the build has nothing to compile.
#
# Xcode Cloud runs this script from the ci_scripts/ directory after cloning.

set -e

echo "post-clone: installing XcodeGen…"
brew install xcodegen

echo "post-clone: generating SmartEars.xcodeproj from project.yml…"
cd "$CI_PRIMARY_REPOSITORY_PATH"
xcodegen generate

echo "post-clone: done."
